;#Ruta pytest.ini (depende del raíz)
;
;[pytest]
;markers =
;    smoke: prueba de validación básica
;    happy_path: tests that validate the core functionality with valid data.
;    error: tests that validate error scenarios with invalid data.
;    create: Tests de creación de aeronaves
;    read: Tests de consulta de aeronaves
;    update: Tests de modificación de aeronaves
;    delete: Tests de eliminación de aeronaves


# Ruta pytest.ini (depende del raíz)

[pytest]
markers =
    smoke: prueba de validación básica
    happy_path: tests that validate the core functionality with valid data.
    error: tests that validate error scenarios with invalid data.
    login: tests relacionados con el login de usuarios
    create: Tests de creación de aeronaves
    read: Tests de consulta de aeronaves
    update: Tests de modificación de aeronaves
    delete: Tests de eliminación de aeronaves

