#Ruta pytest.ini (depende del raíz)

[pytest]
markers =
    smoke: prueba de validación básica
    happy_path: tests that validate the core functionality with valid data.
    error: tests that validate error scenarios with invalid data.